services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pawNetworks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - internal_network
      - frontend_network
       
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - internal_network
      - frontend_network    #to check the databases

  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pawNetworks
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    volumes:
      - image_data:/uploaded_images
    networks:
      - api_network
      - internal_network

  reactapp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reactapp
    ports:
      - "3000:3000"
    depends_on:
      - springboot
    networks:
      - frontend_network
      - api_network

volumes:
  mysql_data:
  image_data:

networks:
  internal_network:
    driver: bridge
  api_network:
    driver: bridge
  frontend_network:
    driver: bridge
